# Generated by Django 3.1.3 on 2020-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='status_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
