# Generated by Django 3.1.3 on 2020-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201203_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='time_off',
            field=models.CharField(max_length=30, verbose_name='Время конца занятия'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='time_on',
            field=models.CharField(max_length=30, verbose_name='Время начала занятия'),
        ),
    ]
